### ISSUE TITLE
Use `Zend\Authentication\AuthenticationService` instead of `ZfcUser`'s

### ISSUE THREAD

**Issue by Ocramius** [bjyoungblood/BjyAuthorize#126]
Starting from ZendFramework 2.1, a `Zend\Authentication\AuthenticationService` should always be available. We should probably move away from the ZfcUser auth service or add a config key to switch the used auth service.

**Comment by Doltsche** [comment]
How can I override the AuthenticationIdentityProviderServiceFactory?

**Comment by gianarb** [comment]
@Doltsche ovveride this key of configuration
https://github.com/bjyoungblood/BjyAuthorize/blob/fb81997c2d904da7b7620da78c0962989ea53dec/config/module.config.php#L74
