### ISSUE TITLE
403 paged not showed up

### ISSUE THREAD

**Issue by pensiero** [bjyoungblood/BjyAuthorize#139]
Hi all,
I have implemented BjyAuthorize, but when I try to access to an unauthorized page, t showed up my 'error/index' page, and not my 'error/403' page.

The Zend Developer toolbar say that i called 3 templates:
layout/layout
error/index
error/403

(i'm using Twig and layout/layout is the root, error/index extend layout/layout and error/403 extend layout/layout)

What could be the problem?

Thanks,
Oscar

**Comment by Albrin** [comment]
As far as I understand this question is actual to those who use Twig?

Code is returned correctly (403 Forbidden), but instead view//403 returns view/index.

![2016-06-19_01-49-52](https://cloud.githubusercontent.com/assets/647103/16173082/edd4f69e-35b7-11e6-9d08-fc5b4cb90f46.png)
