### ISSUE TITLE
Action and BjyAuthorize\Guard\Controller

### ISSUE THREAD

**Issue by mtcocktail** [bjyoungblood/BjyAuthorize#147]
I've problem with BjyAuthorize\Guard\Controller.

If i'm write only controller, roles work perfectly 

```
array('controller' => 'Eridufront\Controller\Index','roles' => array('user')),
```

But if i'm write action 

```
array('controller' => 'Eridufront\Controller\Index','action'=>array('index'),'roles' => array('user')),
```

I've always a forbidden : 

```
You are not authorized to access Eridufront\Controller\Index ::indexAction() .
```

I'm don't understand, i've try many solutions without success... :(

**Comment by gianboschette** [comment]
lçlol99999999999999999999999999999999999999999999999999999999999
