### ISSUE TITLE
Undefined offset: 2

### ISSUE THREAD

**Issue by lawrence615** [bjyoungblood/BjyAuthorize#179]
I am getting an error 'Undefined offset: 2' at the second loop of getRoles() function on ZendDB.php...

I was trying to debug, and when I make a print_r of roleObj, this is what I get

BjyAuthorize\Acl\Role Object
(
    [roleId:protected] => guest
    [parent:protected] => 
)
BjyAuthorize\Acl\Role Object
(
    [roleId:protected] => user
    [parent:protected] => 
)
BjyAuthorize\Acl\Role Object
(
    [roleId:protected] => admin
    [parent:protected] => BjyAuthorize\Acl\Role Object
        (
            [roleId:protected] => 2
            [parent:protected] => 
        )

)

I am not sure but I think the 2 should not be there. This is how my user_role table looked like

+----+---------+-----------------+-------------------+
| id  | role_id | is_default | parent_id |
+----+---------+-----------------+-------------------+
|  1 | guest   |               1 |       NULL |
|  2 | user     |               0 |       NULL |
|  3 | admin   |              0 |        2       |
+----+----------+----------------+---------------+

I changed it to 

+----+---------+-----------------+-------------------+
| id  | role_id | is_default | parent_id |
+----+---------+-----------------+-------------------+
|  1 | guest   |               1 |       NULL |
|  2 | user     |               0 |       NULL |
|  3 | admin   |              0 |        user  |
+----+----------+----------------+---------------+

The error disappeared but am not sure that's how I should do this.

Any help will be appreciated

**Comment by imuneer** [comment]
I had the same issue. It was same as @lawrence615 pointed out. When I changed to "bjyoungblood/bjy-authorize": "dev-master" the error gone.
