### ISSUE TITLE
How to use BjyAuthorize with other model than zfcuser

### ISSUE THREAD

**Issue by Nirzol** [bjyoungblood/BjyAuthorize#202]
Hi alll,
I have my own authentication using zend authentication.
And I wonder how can use BjyAuthorize with that.
I have an user table in DB .

Thanks for help

**Comment by listratov** [comment]
I have connected only after the creation in module.config.php
<code>
    'service_manager' => [
        'factories' =>
            [
                'TestGuardModule\Provider\Identity\TestGuardUserZendDb'
                => 'TestGuardModule\Service\TestGuardUserZendDbIdentityProviderServiceFactory',
            ]
    ]
</code>
and create this classes in ( Provider & Service ) in my TestGuardModule

**Comment by oleglavrik** [comment]
> I have connected only after the creation in module.config.php
'service_manager' => [ 'factories' => [ 'TestGuardModule\Provider\Identity\TestGuardUserZendDb' => 'TestGuardModule\Service\TestGuardUserZendDbIdentityProviderServiceFactory', ] ]
and create this classes in ( Provider & Service ) in my TestGuardModule

I've done like @listratov  and it's works!!! Great, but I don't understand why?
