### ISSUE TITLE
How to set Controller Guard outside of module.config.php

### ISSUE THREAD

**Issue by dennis-fedco** [bjyoungblood/BjyAuthorize#209]
I want to change actions and roles for Controller Guards from my website's admin area.  Is there a way to set these guards dynamically via code?  

Currently there is a static way to set controller guards in `module.config.php` file, but I don't see a way to manipulate them from code.

Poking around in `BjyAuthorize\Module.php` I see `$app->getEventManager()->attach($guard)`.  Not sure if this is is, but I presume that what I want to do is possible. But how, what is the syntax for it, and how can I detach guards as well?

**Comment by mdjaman** [comment]
@dennis-fedco did you finally implement it?

**Comment by dennis-fedco** [comment]
Yes, Maybe.  It has been a while.  It did work, but it is not currently in any kind of production environment.
Why do you ask?

**Comment by mdjaman** [comment]
im asking because im struggling to implement. it would be nice if you have a gist or some codes

**Comment by dennis-fedco** [comment]
Check out [get Rules and Guards from database](http://stackoverflow.com/questions/18264671/zf2-bjyauthorize-get-rules-and-guards-from-database-as-roles-are-already-get), more specifically, my answer there.  Does it have stuff that helps?

**Comment by mdjaman** [comment]
Many thanks @dennis-fedco Have finally implemented it. thanks for your help
