### ISSUE TITLE
Cache in combination with assertions (Serialization of closure)

### ISSUE THREAD

**Issue by japaveh** [bjyoungblood/BjyAuthorize#213]
Hi,

In a large application I'm trying to use assertions on guards and rules. This gives however a problem in combination with the caching. Because the assertions are pulled from the service manager in the following 2 lines

https://github.com/bjyoungblood/BjyAuthorize/blob/master/src/BjyAuthorize/Service/Authorize.php#L345

https://github.com/bjyoungblood/BjyAuthorize/blob/master/src/BjyAuthorize/Service/Authorize.php#L355

it is not possible anymore to serialize the ACL object due to the presence of the closure (the assertion). The trick of applying a Factory to avoid the unwanted serialization doesn't work because the second line (L355) checks if the $assertion is a string and does a second call to the service manager.

Is there any way to avoid this behaviour? 

I am happy to write a PR but I don't directly see what would be the best approach

**Comment by silentvick** [comment]
Since it's a cache-related problem I wonder if there is a way to disable caching ACL at all? It could be an option too.
