### ISSUE TITLE
How to use BjyAuthorize in ZF2 CLI application?

### ISSUE THREAD

**Issue by neetin** [bjyoungblood/BjyAuthorize#223]
A need to run MVC application from CLI. MVC application uses BjyAuthorize very well. But how to authorize a user from command line?

**Comment by SamirBenzenine** [comment]
Small syntax error, it's:

```php
if (!Console::isConsole()) {
    array_unshift($config['modules'],'BjyAuthorize');
}
```

**Comment by saurabhaec** [comment]
how to get config variable. ?

**Comment by novrm** [comment]
In modules.config.php:
`\Zend\Console\Console::isConsole() ? 'ZfcUser' : 'BjyAuthorize'`
