### ISSUE TITLE
Redirect on 403

### ISSUE THREAD

**Issue by gmuehl** [bjyoungblood/BjyAuthorize#24]
Is it possible to redirect to a given Route (zfcuser/login) instead of Showing a 403? Usually this is a better way for the Usability of a Page.

**Comment by miqueiasrafael** [comment]
someone can tell me how can I solve this problem please? An alias "zfcuser Zend_Db_Adapter" was requested but the service could be found.

**Comment by miqueiasrafael** [comment]
It would be great if you had a video BjyAuthorize because it would help a lot! So googled several people downloaded and tried to use the package but on the way encountered several problems when configuring or installing because even the deprecated

**Comment by miqueiasrafael** [comment]
@bjyoungblood  It would be great if you had a video BjyAuthorize because it would help a lot! So googled several people downloaded and tried to use the package but on the way encountered several problems when configuring or installing because even the deprecated
