### ISSUE TITLE
Spécifiy rules and resources from Database

### ISSUE THREAD

**Issue by heronour** [bjyoungblood/BjyAuthorize#245]
Hello;
Can I pic up resources and rules from database and inject theme to configuration or somthing else to change the static way; with config file 

Thanks :)

**Comment by mdjaman** [comment]
Can someone can provide full code with entities please?

**Comment by mdjaman** [comment]
Many thanks to you @heronour

**Comment by zmoukit** [comment]
Hi,

**This another way to spécifiy  resources from Database**

**1 - Create a new file : namespace YOUR_MODULE_NAME\Provider\Resource**
`
namespace YOUR_MODULE_NAME\Provider\Resource;

use BjyAuthorize\Provider\Resource\ProviderInterface;

use YOUR_MODULE_NAME\Service\ResourceService;

/**
 * resource provider from database
 */
class ZendDb implements ProviderInterface
{
	/**
     * @var \Zend\Permissions\Acl\Resource\ResourceInterface[]
     */
    protected $resources = array();
    
	/**
	* @var  \YOUR_MODULE_NAME\Service\ResourceService
	*/
	protected $resourceService;

	public function __construct(ResourceService $resourceService)
	{
         $this->resourceService 	= $resourceService;
	}
	
    /**
     * {@inheritDoc}
     */
    public function getResources()
    {
    	
    	$aResources = $this->resourceService->findAll();
    	
    	foreach($aResources as $resource){
    		$this->resources[$resource->getResourceName()] = array();
    	}
    	
    	return $this->resources;
        
    }
}
`

**2 - Create Factory : namespace YOUR_MODULE_NAME\Factory\Provider**

`
namespace YOUR_MODULE_NAME\Factory\Provider;

use Interop\Container\ContainerInterface;
use Zend\ServiceManager\FactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

use YOUR_MODULE_NAME\Provider\Resource\ZendDb;
use YOUR_MODULE_NAME\Service\ResourceService;

class ZendDbResourceProviderServiceFactory implements FactoryInterface
{
	public function __invoke(ContainerInterface $container, $name, array $options = null)
    {
        return new ZendDb(
			$container->get(ResourceService::class)
		);
    }

    /**
     * Create and return ZendDb instance
     *
     * For use with zend-servicemanager v2; proxies to __invoke().
     *
     * @param ServiceLocatorInterface $container
     * @return ZendDb
     */
    public function createService(ServiceLocatorInterface $container)
    {
        return $this($container, ZendDb::class);
    }
}

`

**3 - YOUR_MODULE_NAME/Module.php**
`
public function getServiceConfig()
 {
	 return array(
		 'factories' => array(
			'YOUR_MODULE_NAME\Provider\Resource\ZendDb' => 'YOUR_MODULE_NAME\Factory\Provider\ZendDbResourceProviderServiceFactory',
		 ),
	 );
 }

`
**4 - config/autoload/module.bjyauthorize.global.php**

`
'resource_providers'    => array(
			/*'BjyAuthorize\Provider\Resource\Config' => array(
            	'YOUR_MODULE_NAME\Controller\Role' => array(),   
            ),*/
		
			'YOUR_MODULE_NAME\Provider\Resource\ZendDb' => array()
        ),

`
