### ISSUE TITLE
package.json specifies PHP requirement 5.3.3 and higher, readme gives example which require PHP 5.5

### ISSUE THREAD

**Issue by akomm** [bjyoungblood/BjyAuthorize#278]
- Array short notation is available in PHP 5.4+
- Scalar name resolution via ::class is available in PHP 5.5+

Should an example not work with PHP versions supported by this package?

**Comment by Ocramius** [comment]
I should just drop < 5.5 support, tbh.

**Comment by stijnhau** [comment]
Just drop it even drop 5.5 not supported anymore by php
