### ISSUE TITLE
Guard run on 'onRoute' event, so if controller/action is not found we can see 'error-unauthorized-controller' error

### ISSUE THREAD

**Issue by oleksii-novikov** [bjyoungblood/BjyAuthorize#279]
Hello

Let's see an exemple
Imagine that there is route 

``` php
test[/:comment[/:action]]
```

config:

``` php
'bjyauthorize' => [
        'guards' => [
            'BjyAuthorize\Guard\Controller' => [
                [
                    'controller' => 'Test\Controller\Comment',
                    'roles' => [],
                ]
        ]
]
```

If we provide controller which is not exists, we will be provided with authorization error (because we don't have rule for non-existent controller)
As I understand, we should be provided with 404 error instead.

I think we can change code in Guard\Controller to next

``` php
public function attach(EventManagerInterface $events)
    {
        $this->listeners[] = $events->attach(MvcEvent::EVENT_DISPATCH, array($this, 'onDispatch'), 2);
    }
```

So in that case, default ZF2 listeners will run first, and only after that Guard will check rights

Thanks

**Comment by Ocramius** [comment]
@hunterok727 this seems like a decent change, though it can't be applied before 2.x due to BC

**Comment by hunterok727** [comment]
Hello, is there any update?

Thanks

**Comment by Ocramius** [comment]
@hunterok727 this has only been labeled for 2.x, but no further work has been done so far.
