### ISSUE TITLE
Exception when using ZfcUserDb Identity provider

### ISSUE THREAD

**Issue by n3vrax** [bjyoungblood/BjyAuthorize#280]
I had a problem with this module when using default zend db identity provider
got an exception as Role with id 'xx' is not found. This happened after trying to login
by digging the code, I've come to this piece of code to be the culprit
found in ZfcUserZendDb provider, in getIdentityRoles method

it returns a list of role ids as found in the link table
but the ids are the integers and it seems it should be the actual role names as found in user_role table

so I created a module to overwrite this class and related factory and config key
what I'm doing is join the user_role table and return the list of actual user role_id(guest, user, admin etc.)

here is the change in the method, so you may check if this is really an issue and correct it in the future

``` php
public function getIdentityRoles()
    {
        $authService = $this->userService->getAuthService();

        if (! $authService->hasIdentity()) {
            return array($this->getDefaultRole());
        }

        // get roles associated with the logged in user
        $sql    = new Sql($this->adapter);
        $select = $sql->select()->from(array('a' => $this->linkTable));
        $select->join($this->roleTable, 'id = a.role_id', array('role_id'));
        $where  = new Where();

        $where->equalTo('a.user_id', $authService->getIdentity()->getId());

        $results = $sql->prepareStatementForSqlObject($select->where($where))->execute();
        $roles     = array();

        foreach ($results as $i) {
            $roles[] = $i['role_id'];
        }
        return $roles;
    }
```

**Comment by danitome24** [comment]
Hi!

I've started with this plugin and I found the same problem. For me this code works!

```php
public function getIdentityRoles()
    {
        $authService = $this->userService->getAuthService();

        if (! $authService->hasIdentity()) {
            return array($this->getDefaultRole());
        }

        // get roles associated with the logged in user
        $sql    = new Sql($this->adapter);
        $select = $sql->select()->from($this->tableName);
        $select->join($this->roleTable, 'id = '. $this->tableName .'.role_id');
        $where  = new Where();

        $where->equalTo($this->tableName .'.user_id', $authService->getIdentity()->getId());

        $results = $sql->prepareStatementForSqlObject($select->where($where))->execute();
        $roles     = array();
        foreach ($results as $i) {
            $roles[] = $i['roleId'];
        }

        return $roles;
    }
```

Hope to be usefull

**Comment by stillatmylinux** [comment]
Thanks @danitome24 worked great. I used your code for ZfcUserZendDb.php.  In addition to your change, I also had to modify 

vendor/bjyoungblood/bjy-authorize/src/BjyAuthorize/Provider/Role/ZendDb.php

`public function getRoles()
    {
        /* @var $adapter \Zend\Db\Adapter\Adapter */
        $adapter      = $this->serviceLocator->get($this->adapterName);
        $tableGateway = new TableGateway($this->tableName, $adapter);
        $sql          = new Select;

        $sql->from($this->tableName);

        $rowset = $tableGateway->selectWith($sql);
        $roles  = array();
        $roles2 = array();
        $count  = 1;

        // Pass One: Build each object
        foreach ($rowset as $row) {
            $roleId = $row[$this->roleIdFieldName];

            $roles[$roleId] = new Role($roleId, $row[$this->parentRoleFieldName]);
            $roles2[$count] = $roleId;
            $count++;
        }

        // Pass Two: Re-inject parent objects to preserve hierarchy
        /* @var $roleObj Role */
        foreach ($roles as $roleObj) {
            $parentRoleObj = $roleObj->getParent();

            if ($parentRoleObj && $parentRoleObj->getRoleId()) {

                $parent = $parentRoleObj->getRoleId();
                
                $parentRoleId = $roles2[(int)$parent];

                $roleObj->setParent($parentRoleId);
            }
        }

        return array_values($roles);
    }`
