### ISSUE TITLE
Provide documentation

### ISSUE THREAD

**Issue by cezarykluczynski** [bjyoungblood/BjyAuthorize#282]
Could you provide more documentation for this module?

The annotated example in the README.md is somewhat misleading, and doesn't explain usage scenarios, just goes through the possibilities.

The wiki examples are very limited.

Is there any more documentation I can dig into?

Integrating this module now is a pain. It just seems like a nice code that nobody ever cared to explain. And, at least in my case, reading it all is not an option.

**Comment by Ocramius** [comment]
The docs we have are all in the readme - most use-cases scenarios are covered by it.

If you want to help out with more docs, please consider creating `.md` files in a `docs/` dir

**Comment by cezarykluczynski** [comment]
I've manage to integrate BjyAuthorize with my app by writing my own identity provider class, but concluding that it's what i need took me a while.
