### ISSUE TITLE
Can't use flashMessenger on RedirectionStrategy

### ISSUE THREAD

**Issue by berturion** [bjyoungblood/BjyAuthorize#290]
Hello,
I made a custom RedirectionStrategy to redirect to my Login page when user is not authorized.
It is the same as `BjyAuthorize\View\RedirectionStrategy` but I added this code to display a message once on my Login page, using FlashMessenger controller plugin:

    (...existing code...)
    $response = $response ?: new Response();
    
    // my code    
    $sm = $event->getApplication()->getServiceManager();
    $flash = $sm->get('ControllerPluginManager')->get('flashMessenger');
    /* @var $flash  \Zend\Mvc\Controller\Plugin\FlashMessenger */
    $flash->addErrorMessage('Not authorized...');
    // END of my code
    
    $response->getHeaders()->addHeaderLine('Location', $url);
    $response->setStatusCode(302);
    (...existing code...)

The layout is normally in charge of displaying them but it's like there isn't any.
Alternatively, how could I pass some parameters in this strategy in order to retrieve them in my login page ?

**Comment by Ocramius** [comment]
> The layout is normally in charge of displaying them but it's like there isn't any.

This needs some debugging, heh :-P We can't possibly know upfront, sorry. Check what is in the session first.

Closing btw: not a repo issue.
