### ISSUE TITLE
Assign diferent roles to one user

### ISSUE THREAD

**Issue by danitome24** [bjyoungblood/BjyAuthorize#291]
Hi all!

In my application I have the following roles:
Admin
user1
user2

When I'm on admin role, i need to change my current role (for a while) to another role (user1 or user2). I need to show, when I'm admin, how can user1 or user2 see my web app.

How can I do this?

Thanks!! Great plugin

**Comment by Ocramius** [comment]
This is currently not possible due to a design flaw in `BjyAuthorize`, and specifically the fact the the `AuthorizeService` is stateful: https://github.com/bjyoungblood/BjyAuthorize/blob/87e10dac52506fe36fa8676292d46a3dce92099d/src/BjyAuthorize/Service/Authorize.php#L207-L219
