### ISSUE TITLE
Exception UnAuthorizedException thrown instead of error/403 template

### ISSUE THREAD

**Issue by danitome24** [bjyoungblood/BjyAuthorize#292]
Hi,

All the module works fine but when a role has no permission to access to a controller, a exception is thrown. Also I want to know how can I change this page to a custom 403 page error.

![image](https://cloud.githubusercontent.com/assets/7501990/9733211/b5479520-5629-11e5-83f3-f50cc45a55b4.png)

Thanks!!
Good job!

**Comment by Ocramius** [comment]
Please check https://github.com/bjyoungblood/BjyAuthorize/blob/master/docs/unauthorized-strategies.md

**Comment by Ocramius** [comment]
Also, you can [set a custom template via configuration overrides](https://github.com/bjyoungblood/BjyAuthorize/blob/87e10dac52506fe36fa8676292d46a3dce92099d/config/module.config.php#L39-L40)

**Comment by danitome24** [comment]
My problem is that this is not the template of the plugin, I think this is a template of Zend Framework, and I can't override it. Any idea?

**Comment by danitome24** [comment]
I've just found how to display the plugin `error/403` template. At method `onDispatchError()` on UnauthorizedStrategy.php i've changed the las lines by:

```php
$model    = new ViewModel($viewVariables);
$viewModel = $event->getViewModel();
$viewModel->setTemplate('error/403');
$viewModel->setVariables($viewVariables);
```

An with that i can see this template:

![image](https://cloud.githubusercontent.com/assets/7501990/9758761/d82a964a-56e8-11e5-8f18-e55a84e79795.png)

**Comment by Ocramius** [comment]
Ah yes, exceptions cannot be caught by the BjyAuthorize strategy, that's indeed true.

What you want is to simply adapt the template to deal with this particular sort of error. You can simply adapt the zf2 template (which is in the skeleton application, btw) to do that

**Comment by danitome24** [comment]
But my question is, where is the exception thrown? On the response?

**Comment by Ocramius** [comment]
@danitome24 the exception may be thrown anywhere, tbh. Usually happens in controller plugins and view helpers btw
