### ISSUE TITLE
Action get have no permissions

### ISSUE THREAD

**Issue by danitome24** [bjyoungblood/BjyAuthorize#294]
Hi!

I'm trying to use bjyauthorize on my web app. The question es that I'm trying to allow the following controller and action : 
`['controller' => 'Intranet\Controller\Login', 'action' => ['role', 'logout'], 'roles' => ['authenticated-user', 'tsqd', 're']]`

But it does not allow me because of appears a resource meant: `'controller/Intranet\Controller\Login:get'`

What is this get action?

Thnks

**Comment by Ocramius** [comment]
@danitome24 it seems like it is a rest controller? What is the route match like, when a failure happens?

**Comment by Voodoo773** [comment]
I have the same problem.

<?php
return [
    'bjyauthorize' => [
        'default_role'       => 'guest',         // not authenticated
        'identity_provider'  => 'IdentitySteam',
        
        'resource_providers' => [
            \BjyAuthorize\Provider\Resource\Config::class => [
                'home' => [],
            ],
        ],
        
        'role_providers' => array(
            \BjyAuthorize\Provider\Role\Config::class => [
                'guest' => [],
                'user'  => ['children' => [
                    'admin' => [],
                ]],
            ],
        ),
        
        'rule_providers' => [
            \BjyAuthorize\Provider\Rule\Config::class => [
                'allow' => [
                    // allow guests and users (and admins, through inheritance)
                    // the "wear" privilege on the resource "pants"
                    [['guest', 'user'], 'home'],
                ],
        
                // Don't mix allow/deny rules if you are using role inheritance.
                // There are some weird bugs.
                'deny' => [
                    // ...
                ],
            ],
        ],
        
        'guards' => array(
            'BjyAuthorize\Guard\Route' => array(
                array('route' => 'home', 'roles' => array('guest', 'admin')),
                array('route'  => 'application', 'roles' => array('guest', 'admin')),
            ),
            'BjyAuthorize\Guard\Controller' => array(
                array(
                    'controller' => 'ApplicationMod\Controller\Index', 
                    'roles' => array('guest', 'user', 'admin'))
            ),
        ),
    ]
]; ?>
<?php //module.config
'router' => array(
        'routes' => array(
            'home' => array(
                'type' => 'Literal',
                'options' => array(
                    'route'    => '/',
                    'defaults' => array(
                        'controller' => 'ApplicationMod\Controller\Index',
                        'action'     => 'index',
                    ),
                ),
            ),
