### ISSUE TITLE
isAllowed only works after reload

### ISSUE THREAD

**Issue by someother1** [bjyoungblood/BjyAuthorize#302]
If i directly write the identity into the storage, the "isAllowed" method only works as desired after a reload.

$oAuth = $this->getAuthenticationService();
$oAuth->getStorage()->write($oUser);

if($this->isAllowed('role', $sRole)) // false, instead of true couse i loaded the identity before

Is there a workaround, or is the reload mandatory?

(i have a different identity interface "class Identity implements \BjyAuthorize\Provider\Identity\ProviderInterface" - may (where?) i need to define that isAllowed should run over this Identity interface?)

**Comment by Ocramius** [comment]
This is a limitation caused by the statefulness of the authorization service provided by this package. It cannot be worked around without a massive redesign.
