### ISSUE TITLE
RedirectionStrategy doesnt work on latest zf2

### ISSUE THREAD

**Issue by someother1** [bjyoungblood/BjyAuthorize#304]
I recently updated all zf & bjyoungblood packages:

```
    "zendframework/zendframework": "2.*",
    "zendframework/zend-developer-tools": "dev-master",
    "doctrine/orm": "2.*",
    "doctrine/migrations" : "dev-master",
    "doctrine/doctrine-orm-module": "0.*",
    "bjyoungblood/bjy-profiler": "1.*",
    "bjyoungblood/bjy-authorize": "1.*",
```

After the upgrade, the redirection strategy doesnt affect any more.

In my "Module.php" i have:

```
    // redirect to home if no access granted
    $oApp = $oMvcEvent->getTarget();
    $oStrategy = new \BjyAuthorize\View\RedirectionStrategy();
    $oStrategy->setRedirectRoute('home');
    $oApp->getEventManager()->attach($oStrategy);
```

If i debug in "\BjyAuthorize\View\RedirectionStrategy::onDispatchError" - the method is never called, i get the "You are not authorized to access {route}" exception from "\vendor\bjyoungblood\bjy-authorize\src\BjyAuthorize\Guard\Route.php" instead :-(

As i only updated my packages i guess the fault is in the compatibility with the new zf2 updates..

Kindly regards

**Comment by Ocramius** [comment]
Possibly a BC break in ZF2?
