### ISSUE TITLE
Use BjyAuthorize with ZF3

### ISSUE THREAD

**Issue by andreidiaconescu** [bjyoungblood/BjyAuthorize#312]
hello,

I heed to use ZF3 in a new project.
How could i use BjyAuthorize with ZF3 ?
When installing BjyAuthorize with composer, using ZF3, it fails with message like 
" bjyoungblood/bjy-authorize 1.4.0-beta1 requires zendframework/zend-servicemanager ~2.1"

If BjyAuthorize cannot be used with zf3, do you know of any other package that does something similar ?

Thank you !

**Comment by Ocramius** [comment]
See #311

Currently not having time to closely follow development, sorry.
