### ISSUE TITLE
Use BjyAuthorize with restful webservice

### ISSUE THREAD

**Issue by ghost** [bjyoungblood/BjyAuthorize#55]
I'm finding a way to use this plugin with restful webservice but still don't know how. When I activate the plugin, the route configuration for restful webservice doesn't work anymore. I request the url, it returns html instead.

Looking forward to your reply @bjyoungblood

**Comment by fiWhy** [comment]
When i try to get access by POST method i catch an forbidden 403 error. How to fix this?

**Comment by Ocramius** [comment]
@fiWhy unrelated.

**Comment by fiWhy** [comment]
I'm sorry. Wrong question. I'm trying to use module with rest api's methods. In case of using get or getList I have access, but when try to send data I catch a forbidden response. Correctly I asked create and update methods.

**Comment by Ocramius** [comment]
@fiWhy open a new issue with more detailed information to reproduce this, please :-\
